#---------------------------------------------
server:
  port: 1570
#---------------------------------------------
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://192.168.1.15:5432/xy_erp?useSSL=false&characterEncoding=UTF-8
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: data-service
#---------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1300/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
#---------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
#---------------------------------------------
#security:
#  oauth2:
#    resource:
#      id: ${spring.application.name}
#      user-info-uri: http://192.168.1.10:1360/user
#    client:
#      client-id: xinyuan
#      client-secret: xinyuan1525
#---------------------------------------------
